controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_01_controller:
      type: forward_command_controller/ForwardCommandController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
      
joint_01_controller:
  ros__parameters:
    joints:
      - arm_joint_01
    interface_name: velocity
    command_interfaces:
      - velcoity 
    state_interfaces:
      - position
      - velocity

